'use client';

import React, { useState } from 'react';
import { X, Download, Copy, Check, FileJson, FileText } from 'lucide-react';
import { AuditSummary } from '@/types/audit';

interface ExportModalProps {
  summary: AuditSummary;
  isOpen: boolean;
  onClose: () => void;
}

export const ExportModal: React.FC<ExportModalProps> = ({ summary, isOpen, onClose }) => {
  const [format, setFormat] = useState<'markdown' | 'json'>('markdown');
  const [copied, setCopied] = useState<boolean>(false);

  if (!isOpen) return null;

  const generateMarkdownReport = (): string => {
    return `# PromptShield Arena - Security Audit & Hardening Report

**Audit ID:** \`${summary.audit_id}\`  
**Timestamp:** \`${summary.timestamp}\`  
**Initial Safety Score:** **${summary.initial_safety_score}%**  
**Post-Hardened Safety Score:** **${summary.post_safety_score}%**  
**Net Improvement Delta:** **+${summary.score_delta}%**  
**Total Attacks Evaluated:** ${summary.total_attacks}  

---

## 1. Executive Summary

- **Baseline Prompt Vulnerabilities:** ${summary.initial_failed_count} adversarial breaches detected.
- **Post-Hardening Vulnerabilities:** ${summary.post_failed_count} unresolved breaches.
- **Defensive Patches Applied:**
${summary.hardening_changes.map((c) => `  - ${c}`).join('\n')}

---

## 2. Hardened System Prompt (Compiled)

\`\`\`xml
${summary.hardened_prompt}
\`\`\`

---

## 3. Adversarial Test Suite Results

| ID | Vector Category | Baseline Status | Hardened Status | Description |
|---|---|---|---|---|
${summary.attacks
  .map((a) => {
    const init = summary.initial_evaluations.find((e) => e.attack_id === a.id);
    const post = summary.post_evaluations.find((v) => v.attack_id === a.id);
    return `| ${a.id} | \`${a.category}\` | ${init?.passed ? '✅ Blocked' : '❌ Breached'} | ${post?.passed ? '✅ Secured' : '❌ Breached'} | ${a.description || a.prompt.slice(0, 40)}... |`;
  })
  .join('\n')}

---
*Report generated by PromptShield Arena Autonomous Security Engine.*
`;
  };

  const content =
    format === 'markdown'
      ? generateMarkdownReport()
      : JSON.stringify(summary, null, 2);

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const ext = format === 'markdown' ? 'md' : 'json';
    const mime = format === 'markdown' ? 'text/markdown' : 'application/json';
    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `PromptShield_Audit_${summary.audit_id}.${ext}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4 backdrop-blur-sm">
      <div className="flex h-[80vh] w-full max-w-3xl flex-col rounded-2xl border border-zinc-800 bg-zinc-950 p-6 shadow-2xl">
        {/* Modal Header */}
        <div className="flex items-center justify-between border-b border-zinc-800 pb-4">
          <div className="flex items-center gap-2">
            <span className="text-sm font-bold uppercase tracking-wider text-cyan-400">
              Export Audit Report
            </span>
            <span className="text-xs font-mono text-zinc-500">[{summary.audit_id}]</span>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="rounded-lg p-1 text-zinc-400 hover:bg-zinc-800 hover:text-white"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Format Selector & Actions */}
        <div className="flex items-center justify-between py-3">
          <div className="flex rounded-lg border border-zinc-800 bg-zinc-900 p-0.5 text-xs">
            <button
              type="button"
              onClick={() => setFormat('markdown')}
              className={`flex items-center gap-1.5 rounded-md px-3 py-1.5 transition-colors ${
                format === 'markdown'
                  ? 'bg-zinc-800 text-white font-medium'
                  : 'text-zinc-400 hover:text-zinc-200'
              }`}
            >
              <FileText className="h-3.5 w-3.5" />
              Markdown Report
            </button>
            <button
              type="button"
              onClick={() => setFormat('json')}
              className={`flex items-center gap-1.5 rounded-md px-3 py-1.5 transition-colors ${
                format === 'json'
                  ? 'bg-zinc-800 text-white font-medium'
                  : 'text-zinc-400 hover:text-zinc-200'
              }`}
            >
              <FileJson className="h-3.5 w-3.5" />
              Raw JSON
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleCopy}
              className="flex items-center gap-1.5 rounded-lg border border-zinc-800 bg-zinc-900 px-3 py-1.5 text-xs text-zinc-200 hover:bg-zinc-800"
            >
              {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
              <span>{copied ? 'Copied!' : 'Copy'}</span>
            </button>

            <button
              type="button"
              onClick={handleDownload}
              className="flex items-center gap-1.5 rounded-lg bg-cyan-500 px-3 py-1.5 text-xs font-semibold text-zinc-950 hover:bg-cyan-400"
            >
              <Download className="h-3.5 w-3.5" />
              <span>Download File</span>
            </button>
          </div>
        </div>

        {/* Content Preview */}
        <div className="flex-1 overflow-auto rounded-xl border border-zinc-800 bg-zinc-900/50 p-4 font-mono text-xs text-zinc-300">
          <pre className="whitespace-pre-wrap">{content}</pre>
        </div>
      </div>
    </div>
  );
};
